# OWASP ZAP Baseline configuration
# IGNORE rules that are false positives in our isolated test environment
10020	IGNORE	(X-Frame-Options Header Scanner)
10021	IGNORE	(X-Content-Type-Options Header Missing)
